Round setup and battle timers
shashahchk/omegacity-phaser pull request #15
Opened 2024-02-20 04:20 UTC by shashahchk

Set up round by 
1. put monsters at random positions
2. restart the scene

Add timers to start new round when round is over.

2024-02-20 15:34 UTC, winson8222 requested changes
Thanks for making the random monsters spawn logics. Just wondering if the resolution of the game changed do we need to change all the offsets of the tilemap? I am not sure if after merging mine it will cause the map to explode.

2024-02-20 15:34 UTC, winson8222 commented on client/src/scenes/Battle.ts
> +        this.cursors = this.input.keyboard.createCursorKeys()
Lets standardise to put those that can be loaded, like cursor/keyboard input into the preload?

2024-02-20 15:34 UTC, winson8222 commented on client/src/scenes/Battle.ts
> +    private setUpMap(xOffset: number, yOffset: number) {
There is no collision set with the player, is it omitted on purpose?

2024-02-20 15:34 UTC, winson8222 commented on client/public/enemies/dragon.png
beautiful

2024-02-21 15:48 UTC, closed without merging

2024-02-21 15:48 UTC, yongning0310 commented
pending bug fixes