Add a ButtonCreator component, update to UI
shashahchk/omegacity-phaser pull request #32
Opened 2024-02-23 01:09 UTC by KinTatHo

JoinQueue and LeaveQueue now has buttons, and will not be overshadowed by walls

2024-02-23 01:48 UTC, KinTatHo commented
Create a username popup

Users are now prompted to enter their username before joining the game

2024-02-23 11:51 UTC, winson8222 requested changes
Very nice looking buttons, maybe can disable player movement when entering the username.

2024-02-23 11:51 UTC, winson8222 commented on client/package-lock.json
> -			"dev": true,
How come this is added suddenly.

2024-02-23 11:51 UTC, winson8222 commented on client/src/components/ButtonCreator.tsx
> +        fontSize: "11px",
If can cutomise the button size lets make font size customisabale also. This is a really useful creation function though.

2024-02-23 11:51 UTC, winson8222 commented on client/src/scenes/Game.ts
> +      .setScrollFactor(0)
What is this change for?

2024-02-28 15:01 UTC, winson8222 approved these changes

2024-02-28 15:23 UTC, merged