Feature new schema
shashahchk/omegacity-phaser pull request #42
Opened 2024-02-26 11:27 UTC by winson8222

- Added schema according to the new structure
- Integrated with BattleRoom
- Timer not showing yet

2024-02-27 06:11 UTC, shashahchk requested changes
Thanks a lot for the detailed schema and for updating the rest of the code to adhere to the schema. 
Just a few concerns about making certain types stricter to avoid problems in the future. These should be easy fixes. Also one main thing (deletion of player) that should be implemented correctly.

2024-02-27 06:11 UTC, shashahchk commented on .idea/shelf/Uncommitted_changes_before_Checkout_at_14_2_24__5_45_pm__Changes_.xml
can we remove these? Or should commit again

2024-02-27 06:11 UTC, shashahchk commented on server/src/rooms/schema/Character.ts
> +  @type("string") lastMovedTime: string;
note how this lastMovedTime is string, but the curRoundStartTime in BattleRoomState is number. Should try to be consistent?

2024-02-27 06:11 UTC, shashahchk commented on server/src/rooms/schema/Character.ts
> +  @type(["string"]) playersTackling = new ArraySchema<string>();
should we name as playerIdsTackling?

2024-02-27 06:11 UTC, shashahchk commented on server/src/rooms/schema/Character.ts
> +  @type(["number"]) questionsSolved: number; // abit sus but we'll see
for all these names, can consider the use of id to differnetiate the Object from the ID,
in this case is it better to use questionIdsSolved?
consider this for all other fields as well

2024-02-27 06:11 UTC, shashahchk commented on server/src/rooms/schema/Group.ts
> +  @type("string") teamColor: string;
consider using enum for more safety.

2024-02-27 06:11 UTC, shashahchk commented on server/src/rooms/BattleRoom.ts
> +    this.state.teams[0].teamPlayers.delete(client.sessionId);
try not to hardcode this. 
There should be a way to retrieve the InBattlePlayer from the sessionId (can get this from the map in room state)
From that, we retrieve player.teamId,
then delete accordingly

2024-02-27 06:11 UTC, shashahchk commented on server/src/rooms/schema/BattleRoomState.ts
> +  @type("string") currentGameState: string;
can consider using enum for more safety

2024-02-27 06:11 UTC, shashahchk commented on server/src/rooms/schema/MyRoomState.ts
>    @type({ map: Player }) players = new MapSchema<Player>();
this is the map i am referring to that maps sessionId/playerId to player Object. I'm not entirely sure on this. But this should allow u to handle the deletion of player when they leave battle nicely.

2024-02-27 19:25 UTC, yongning0310 commented
please pull and run the code before merging, im not sure if its correct cos i had to resolve merge conflict for parts of code that id3k whats gg on

2024-02-28 05:04 UTC, yongning0310 commented
fix animation bug too

2024-02-28 06:01 UTC, shashahchk requested changes
(to yongning) Direction and animations works well. There is collision box bug. Namely when press left, probably due to the offset, (find out more about phaser physics collider). Also collision box for faune is sometimes not consistent size.

2024-02-28 08:45 UTC, merged